
//User

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";

export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";

export const EDIT_USER_REQUEST = "EDIT_USER_REQUEST";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAILURE = "EDIT_USER_FAILURE";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

//Client
export const CREATE_USERCLIENT_REQUEST = "CREATE_USERCLIENT_REQUEST";
export const CREATE_USERCLIENT_SUCCESS = "CREATE_USERCLIENT_SUCCESS";
export const CREATE_USERCLIENT_FAILURE = "CREATE_USERCLIENT_FAILURE";

export const FETCH_USERSCLIENT_REQUEST = "FETCH_USERSCLIENT_REQUEST";
export const FETCH_USERSCLIENT_SUCCESS = "FETCH_USERSCLIENT_SUCCESS";
export const FETCH_USERSCLIENT_FAILURE = "FETCH_USERSCLIENT_FAILURE";

export const EDIT_USERCLIENT_REQUEST = "EDIT_USERCLIENT_REQUEST";
export const EDIT_USERCLIENT_SUCCESS = "EDIT_USERCLIENT_SUCCESS";
export const EDIT_USERCLIENT_FAILURE = "EDIT_USERCLIENT_FAILURE";

export const DELETE_USERCLIENT_REQUEST = "DELETE_USERCLIENT_REQUEST";
export const DELETE_USERCLIENT_SUCCESS = "DELETE_USERCLIENT_SUCCESS";
export const DELETE_USERCLIENT_FAILURE = "DELETE_USERCLIENT_FAILURE";

//Location
export const CREATE_LOCATION_REQUEST = "CREATE_LOCATION_REQUEST";
export const CREATE_LOCATION_SUCCESS = "CREATE_LOCATION_SUCCESS";
export const CREATE_LOCATION_FAILURE = "CREATE_LOCATION_FAILURE";

export const FETCH_LOCATION_REQUEST = "FETCH_LOCATION_REQUEST";
export const FETCH_LOCATION_SUCCESS = "FETCH_LOCATION_SUCCESS";
export const FETCH_LOCATION_FAILURE = "FETCH_LOCATION_FAILURE";

export const EDIT_LOCATION_REQUEST = "EDIT_LOCATION_REQUEST";
export const EDIT_LOCATION_SUCCESS = "EDIT_LOCATION_SUCCESS";
export const EDIT_LOCATION_FAILURE = "EDIT_LOCATION_FAILURE";

export const DELETE_LOCATION_REQUEST = "DELETE_LOCATION_REQUEST";
export const DELETE_LOCATION_SUCCESS = "DELETE_LOCATION_SUCCESS";
export const DELETE_LOCATION_FAILURE = "DELETE_LOCATION_FAILURE";